services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
