replicaCount: 1

image:
  repository: rag_project-rag-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 800m
    memory: 1Gi

config:
  STREAMLIT_SERVER_PORT: "8000"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  GOOGLE_CHAT_MODEL: gemini-2.0-flash
  GOOGLE_EMBEDDING_MODEL: models/gemini-embedding-001

secret:
  create: true
  data:
    GOOGLE_API_KEY: staging-placeholder
    COHERE_API_KEY: staging-placeholder
    TOGETHER_API_KEY: staging-placeholder
    HF_API_KEY: staging-placeholder
    GROQ_API_KEY: staging-placeholder
    GITHUB_MODELS_TOKEN: staging-placeholder

persistence:
  enabled: true
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /app/data
