apiVersion: v1
kind: Secret
metadata:
  name: rag-app-secrets
  namespace: rag-mvp
  labels:
    app.kubernetes.io/name: rag-project
type: Opaque
stringData:
  GOOGLE_API_KEY: "<replace-google-api-key>"
  COHERE_API_KEY: "<replace-cohere-api-key>"
  TOGETHER_API_KEY: "<replace-together-api-key>"
  HF_API_KEY: "<replace-hf-api-key>"
  GROQ_API_KEY: "<replace-groq-api-key>"
  GITHUB_MODELS_TOKEN: "<replace-github-models-token>"
