apiVersion: v1
kind: Service
metadata:
  name: rag-app-svc
  namespace: rag-mvp
  labels:
    app.kubernetes.io/name: rag-project
spec:
  selector:
    app: rag-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
